services:
  collectionbuilder:
    platform: linux/amd64
    container_name: collectionbuilder
    image: dhilsfu/collectionbuilder-docker
    ports:
      - 4000:4000
    volumes:
      # override specific content folders with demo content
      - ./app/_data:/app/_data
      - ./app/objects:/app/objects
      - ./app/pages:/app/pages
      - ./app/_config.yml:/app/_config.yml
      - ./app/favicon.ico.yml:/app/favicon.ico

      # don't touch the _site folder
      - /app/_site
    environment:
      - METADATA_FILE_URL=https://docs.google.com/spreadsheets/d/e/2PACX-1vQ-ObrBYNpd77GWsWu1WYReYw6AEOde_zVay6KRVXimG913YNp9J5fR6qQMOizAs9A2EznC7aIVOlrX/pub?gid=0&single=true&output=csv
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:4000/ || exit 1"]
      interval: 2s
      retries: 120